# This is a basic workflow to help you get started with Actions

name: Deploy static site content

# Controls when the action will run. Triggers the workflow on push events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy files via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LT_VU_MIF_GRIMSA_WEB_HOST }}
          username: ${{ secrets.LT_VU_MIF_GRIMSA_USERNAME }}
          password: ${{ secrets.LT_VU_MIF_GRIMSA_PASSWORD }}
          port: ${{ secrets.LT_VU_MIF_GRIMSA_SSH_PORT }}
          source: "index.html,se,research,googlef2f53d0c3856c5be.html"
          target: "www"
          rm: true
